### ISSUE TITLE
Errors during install, ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by b8vr** [lovelykd/sqlcipher-cli#7]
$ sudo npm i -g sqlcipher-cli

npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
/usr/local/bin/sqlcipher-cli -> /usr/local/lib/node_modules/sqlcipher-cli/index.js

> @journeyapps/sqlcipher@4.1.0 install /usr/local/lib/node_modules/sqlcipher-cli/node_modules/@journeyapps/sqlcipher
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Pre-built binaries not installable for @journeyapps/sqlcipher@4.1.0 and node@10.19.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/usr/local/lib/node_modules/sqlcipher-cli/node_modules/@journeyapps/sqlcipher/lib/binding'
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/sqlcipher-cli/node_modules/@journeyapps/sqlcipher/build'
gyp ERR! System Linux 5.4.0-144-generic
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "configure" "--fallback-to-build" "--module=/usr/local/lib/node_modules/sqlcipher-cli/node_modules/@journeyapps/sqlcipher/lib/binding/node-v64-linux-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/usr/local/lib/node_modules/sqlcipher-cli/node_modules/@journeyapps/sqlcipher/lib/binding/node-v64-linux-x64" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
gyp ERR! cwd /usr/local/lib/node_modules/sqlcipher-cli/node_modules/@journeyapps/sqlcipher
gyp ERR! node -v v10.19.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/bin/node-gyp configure --fallback-to-build --module=/usr/local/lib/node_modules/sqlcipher-cli/node_modules/@journeyapps/sqlcipher/lib/binding/node-v64-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/usr/local/lib/node_modules/sqlcipher-cli/node_modules/@journeyapps/sqlcipher/lib/binding/node-v64-linux-x64 --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/sqlcipher-cli/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Linux 5.4.0-144-generic
node-pre-gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/sqlcipher-cli/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/sqlcipher-cli/node_modules/@journeyapps/sqlcipher
node-pre-gyp ERR! node -v v10.19.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/node /usr/bin/node-gyp configure --fallback-to-build --module=/usr/local/lib/node_modules/sqlcipher-cli/node_modules/@journeyapps/sqlcipher/lib/binding/node-v64-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/usr/local/lib/node_modules/sqlcipher-cli/node_modules/@journeyapps/sqlcipher/lib/binding/node-v64-linux-x64 --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @journeyapps/sqlcipher@4.1.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @journeyapps/sqlcipher@4.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-03-05T11_02_45_887Z-debug.log

**Comment by lovelykd** [comment]
> gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/sqlcipher-cli/node_modules/@journeyapps/sqlcipher/build'

Hi @Soren17 , it looks that there was a permission issue, could you double check whether you used `sudo`?
